spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=8080

openai.api.key=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
