spring.datasource.url=jdbc:mysql://localhost:3306/ai_resume_db
spring.datasource.username=root
spring.datasource.password=Rishi@3043

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

openai.api.key=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
